accounts/urls.py
from django.urls import path, re_path
from accounts import views
from django.contrib.auth import views as auth_views

app_name = 'accounts'

urlpatterns = [
    re_path(r'^signup/$', views.signup, name='signup'),
    re_path(r'^login/$', auth_views.LoginView.as_view(
        template_name='accounts/login.html'), name='login'),
    re_path(r'^logout/$', auth_views.LogoutView.as_view(), name='logout'),
    #re_path(r'^my-profile/$', views.ProfileDetailView.as_view(), name='my_profile'),
    re_path(r'^update-profile/$', views.update_profile, name='update_profile'),
    re_path(r'^profile/(?P<pk>\d+)/$',
            views.ProfileDetailView.as_view(), name='view_profile_with_pk'),
    re_path(r'^change-password/$', views.MyPasswordChangeView.as_view(),
            name='change_password'),
    re_path(r'^password_reset/$', views.MyPasswordResetView.as_view(),
            name='password_reset'),
    re_path(r'^password_reset/done/$',
            views.MyPasswordResetDoneView.as_view(), name='password_reset_done'),
    re_path(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
            views.MyPasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    re_path(r'^reset/done/$', views.MyPasswordResetCompleteView.as_view(),
            name='password_reset_complete'),
]

file_upload_app/urls.py
from django.urls import re_path
from file_upload_app import views

app_name = 'album'

urlpatterns = [
    re_path(r'^album-upload/$', views.album_upload, name='album_upload'),
    re_path(r'^avatar-upload/$', views.avatar_upload, name='avatar_upload'),
    re_path(r'^album-view-by-folder/(?P<folder_name>\d+)/$', views.album_view_by_folder, name='album_view_by_folder'),
    re_path(r'^view/(?P<user>\d+)/$', views.AlbumView.as_view(), name='album_view'),
    re_path(r'^delete/(?P<image_pk>\d+)/$', views.delete_image, name='delete_image'),
]

my_django_project/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from . import settings
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    re_path(r"^$", views.HomePage.as_view(), name="home"),
    path('accounts/', include('accounts.urls')),
    path('album/', include('file_upload_app.urls')),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

file_upload_app/models.py
from django.db import models
from django.contrib.auth.models import User

from .validators import FileValidator

file_validator = FileValidator(max_size=2500 * 2000,
                                        content_types=('image/jpeg', 'image/gif', 'image/png'))


def user_directory_path(instance, filename):
    """Creates a path string to upload a file to a folder
    associated with the user id"""
    if isinstance(instance, AvatarImage):
        return f'avatars/user_{instance.user.id}/{filename}'
    elif isinstance(instance, AlbumFile):
        return f'albums/user_{instance.user.id}/{filename}'


class AbstractImage(models.Model):
    description = models.CharField(max_length=255)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    image = models.FileField(
        upload_to=user_directory_path,
        validators=[file_validator, ]
    )
    uploaded_at = models.DateTimeField(auto_now=True)

    def delete(self, using=None, keep_parents=False):
        self.image.storage.delete(self.image.name)
        super().delete()

    class Meta:
        abstract = True


class AlbumFile(AbstractImage):
    pass


class AvatarImage(AbstractImage):
    description = models.CharField(max_length=255, default='')

file_upload_app/forms.py
from django import forms
from .models import AlbumFile, AvatarImage


class AlbumForm(forms.ModelForm):
    class Meta:
        model = AlbumFile
        fields = ['description', 'image',]


class AvatarForm(forms.ModelForm):
    class Meta:
        model = AvatarImage
        fields = ['image',]

file_upload_app/views.py
from os import listdir
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from django.conf import settings
from django.views import generic
from django.contrib.auth.decorators import login_required

from .models import AlbumFile
from .forms import AlbumForm, AvatarForm


@login_required
def album_upload(request):
    if request.method == 'POST':
        form = AlbumForm(request.POST, request.FILES)
        if form.is_valid():
            image = form.save(commit=False)
            image.user = request.user
            image.save()
            return redirect('album:album_view', user=request.user.id)
    else:
        form = AlbumForm()
    return render(request, 'album_upload.html', {
        'form': form
    })


@login_required
def avatar_upload(request):
    if request.method == 'POST':
        form = AvatarForm(request.POST, request.FILES)
        if form.is_valid():
            image = form.save(commit=False)
            image.user = request.user
            image.save()
            return redirect('accounts:view_profile_with_pk', pk=request.user.id)
    else:
        form = AvatarForm()
    return render(request, 'avatar_upload.html', {
        'form': form
    })


def album_view_by_folder(request, folder_name):
    path = settings.MEDIA_ROOT
    img_list = listdir(path + f'/user_{folder_name}')
    image_folder = settings.MEDIA_URL + f'user_{folder_name}/'
    context = {'images': img_list, 'image_folder': image_folder}
    return render(request, 'album_view_by_folder.html', context)


class AlbumView(generic.ListView):
    model = AlbumFile
    context_object_name = 'images'
    template_name = 'album_view.html'

    def get_queryset(self):
        return AlbumFile.objects.filter(user=self.kwargs['user']).order_by('-uploaded_at')[:5]


def delete_image(request, image_pk):
    image = AlbumFile.objects.get(pk=image_pk).delete()
    return redirect('album:album_view', user=request.user.id)

file_upload_app/templates/album_upload.html
{% extends 'base.html'%}
{% load bootstrap4 %}


{% block content %}
<div class="container">
    <h1>Upload:</h1>
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {% bootstrap_form form %}
        <input type="submit" value="Upload" class="btn btn-default">
    </form>
</div>
{% endblock %}

file_upload_app/templates/album_view.html
{% extends 'base.html'%}
{% load bootstrap4 %}


{% block content %}
<div class="container">
    <div class="row">
        {% if images %}
	{% for image in images %}
	
            <div class="col-md-4">
              <div class="card mb-4 box-shadow">
                <img class="card-img-top" src="{{ image.image.url }}" alt="{{ image }}">
                <div class="card-body">
                  <p class="card-text">{{ image.description }}</p>
                  <div class="d-flex justify-content-between align-items-center">
                    <div class="btn-group">
                      <button type="button" class="btn btn-sm btn-outline-secondary">View</button>
                      {% if user.is_authenticated and image.user.id == user.id %}
                      <a href="{% url 'album:delete_image' image_pk=image.id %}"><button type="button" class="btn btn-sm btn-outline-secondary">Delete</button></a>
                      {% endif %}
                    </div>
                    <small class="text-muted">9 mins</small>
                  </div>
                </div>
              </div>
            </div>
        {% endfor %}

    
{% else %}
	<p>No image available.</p>
{% endif %}
<br>

</div>
<a href="{% url 'album:album_upload' %}"><button type="button" class="btn btn-info">Go to upload</button></a>

{% endblock %}

file_upload_app/templates/avatar_upload.html
{% extends 'base.html'%}
{% load bootstrap4 %}


{% block content %}
<div class="container">
    <h1>Upload:</h1>
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {% bootstrap_form form %}
        <input type="submit" value="Upload" class="btn btn-default">
    </form>
</div>
{% endblock %}