accounts/urls.py
from django.urls import path, re_path
from accounts import views
from django.contrib.auth import views as auth_views

app_name = 'accounts'

urlpatterns = [
    re_path(r'^signup/$', views.signup, name='signup'),
    re_path(r'^login/$', auth_views.LoginView.as_view(
        template_name='accounts/login.html'), name='login'),
    re_path(r'^logout/$', auth_views.LogoutView.as_view(), name='logout'),
    #re_path(r'^my-profile/$', views.ProfileDetailView.as_view(), name='my_profile'),
    re_path(r'^update-profile/$', views.update_profile, name='update_profile'),
    re_path(r'^profile/(?P<pk>\d+)/$',
            views.ProfileDetailView.as_view(), name='view_profile_with_pk'),
    re_path(r'^change-password/$', views.MyPasswordChangeView.as_view(),
            name='change_password'),
    re_path(r'^password_reset/$', views.MyPasswordResetView.as_view(),
            name='password_reset'),
    re_path(r'^password_reset/done/$',
            views.MyPasswordResetDoneView.as_view(), name='password_reset_done'),
    re_path(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
            views.MyPasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    re_path(r'^reset/done/$', views.MyPasswordResetCompleteView.as_view(),
            name='password_reset_complete'),
]

file_upload_app/urls.py
from django.urls import re_path
from file_upload_app import views

app_name = 'album'

urlpatterns = [
    re_path(r'^album-upload/$', views.album_upload, name='album_upload'),
    re_path(r'^avatar-upload/$', views.avatar_upload, name='avatar_upload'),
    re_path(r'^album-view-by-folder/(?P<folder_name>\d+)/$', views.album_view_by_folder, name='album_view_by_folder'),
    re_path(r'^view/(?P<user>\d+)/$', views.AlbumView.as_view(), name='album_view'),
    re_path(r'^delete/(?P<image_pk>\d+)/$', views.delete_image, name='delete_image'),
]

my_django_project/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from . import settings
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    re_path(r"^$", views.HomePage.as_view(), name="home"),
    path('accounts/', include('accounts.urls')),
    path('album/', include('file_upload_app.urls')),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    description = models.CharField(max_length=100, default='')
    home_city = models.CharField(max_length=150, default='')

    def __str__(self):
        return self.user.username

def create_profile(sender, **kwargs):
    if kwargs['created']:
        profile = Profile.objects.create(user=kwargs['instance'])

post_save.connect(create_profile, sender=User)

accounts/forms.py
from django import forms
from django.contrib.auth.models import User
from accounts.models import Profile
from django.contrib.auth.forms import UserCreationForm, PasswordChangeForm


class SignupForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = (
            'username',
            'first_name',
            'last_name',
            'email',
            'password1',
            'password2'
        )

    def save(self, commit=True):
        user = super(SignupForm, self).save(commit=False)
        user.first_name = self.cleaned_data['first_name']
        user.last_name = self.cleaned_data['last_name']
        user.email = self.cleaned_data['email']

        if commit:
            user.save()

        return user


class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email')


class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ('description', 'home_city')

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from django.urls import reverse, reverse_lazy
from django.views.generic import TemplateView
from django.contrib.auth.views import (
    PasswordChangeView,
    PasswordResetView,
    PasswordResetDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView
)
from django.db import transaction
from django.contrib.auth.decorators import login_required

from accounts.forms import SignupForm, UserForm, ProfileForm
from file_upload_app.models import AvatarImage


def signup(request):
    if request.method == 'POST':
        form = SignupForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(reverse('home'))
    else:
        form = SignupForm()
        args = {'form': form}
    return render(request, 'accounts/signup.html', args)


class ProfileDetailView(TemplateView):
    template_name = 'accounts/my_profile.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if context.get('pk'):
            context['user'] = User.objects.get(pk=self.kwargs.get('pk'))
            try:
                avatar = AvatarImage.objects.filter(
                    user=self.kwargs.get('pk')).order_by('-uploaded_at')[0]
            except IndexError:
                avatar = None
            context['avatar'] = avatar
            return context
        else:
            context['user'] = self.request.user

        print('===', context)

        return context


@login_required
@transaction.atomic
def update_profile(request):
    if request.method == 'POST':
        user_form = UserForm(request.POST, instance=request.user)
        profile_form = ProfileForm(request.POST, instance=request.user.profile)
        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            messages.success(request, 'Your profile was successfully updated!')
            return redirect('accounts:my_profile')
        else:
            messages.error(request, 'Please correct the error below.')
    else:
        user_form = UserForm(instance=request.user)
        profile_form = ProfileForm(instance=request.user.profile)
    return render(request, 'accounts/update_profile.html', {
        'user_form': user_form,
        'profile_form': profile_form
    })


class MyPasswordChangeView(PasswordChangeView):
    template_name = 'accounts/password_change.html'
    success_url = reverse_lazy('home')


class MyPasswordResetView(PasswordResetView):
    template_name = 'accounts/password_reset.html'
    success_url = reverse_lazy('home')
    email_template_name = 'accounts/password_reset_email.html'
    subject_template_name = 'accounts/password_reset_subject.txt'


class MyPasswordResetDoneView(PasswordResetDoneView):
    template_name = 'accounts/password_reset_done.html'


class MyPasswordResetConfirmView(PasswordResetConfirmView):
    template_name = 'accounts/password_reset_confirm.html'
    success_url = reverse_lazy('accounts:password_reset_complete')


class MyPasswordResetCompleteView(PasswordResetCompleteView):
    template_name = 'accounts/password_reset_complete.html'

accounts/templates/accounts/login.html
{% extends 'base.html'%}
{% load bootstrap4 %}


{% block content %}
<div class="container">
    <h1>Login:</h1>
    <form method="POST">
        {% csrf_token %}
        {% bootstrap_form form %}
        <input type="submit" value="Login" class="btn btn-default">
    </form>
</div>
{% endblock %}

accounts/templates/accounts/my_profile.html
{% extends 'base.html'%}
{% load bootstrap4 %}
{% load static %}


{% block content %}
<div class="container">
    {% if user.is_authenticated%}
    <p>Email: {{ user.email }}</p>
    <p>City: {{ user.profile.home_city }}</p>
    {% if avatar %}
    <a href="{% url 'album:avatar_upload' %}"><img src="{{ avatar.image.url }}" alt="{{ avatar }}" class="img-thumbnail" width=200px></a>
    {% else %}
    <a href="{% url 'album:avatar_upload' %}"><img src="{% static "accounts/default_avatar.png" %}" alt="Default" class="img-thumbnail" width=200px></a>
    {% endif %}
    <br>
    {% if user.is_authenticated and request.user.pk == user.pk %}
        <a class="btn btn-outline-secondary" href="{% url "accounts:update_profile" %}" role="button">Update Profile</a>
    {% endif %}
    {% else %}
        <a href="{% url "accounts:login" %}"><h3> Please login </h3></a>
    {% endif %}

</div>
{% endblock %}

accounts/templates/accounts/password_change.html
{% extends 'base.html'%}
{% load bootstrap4 %}


{% block content %}
<div class="container">
    <h1>Change password:</h1>
    <form method="POST">
        {% csrf_token %}
        {% bootstrap_form form %}
        <input type="submit" value="Submit" class="btn btn-default">
    </form>
</div>
{% endblock %}

accounts/templates/accounts/password_reset.html
{% extends 'base.html'%} {
{% load bootstrap4 %} 
{% block content %}
<div class="container">
  <h3>Forgot password</h3>
  <form method="post">
    {% csrf_token %} 
    {% bootstrap_form form %}
    <button type="submit">Submit</button>
  </form>
</div>
{% endblock %}

accounts/templates/accounts/password_reset_complete.html
{% extends 'base.html'%}


{% block content %}
  <p>
    Your password has been set. You may go ahead and <a href="{% url 'accounts:login' %}">sign in</a> now.
  </p>
{% endblock %}

accounts/templates/accounts/password_reset_confirm.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}
  {% if validlink %}
    <h3>Change password</h3>
    <form method="post">
      {% csrf_token %}
      {% bootstrap_form form %}
      <button type="submit">Change password</button>
    </form>
  {% else %}
    <p>
      The password reset link was invalid, possibly because it has already been used.
      Please request a new password reset.
    </p>
  {% endif %}
{% endblock %}

accounts/templates/accounts/password_reset_done.html
{% extends 'base.html' %}

{% block content %}
  <p>
    We've emailed you instructions for setting your password, if an account exists with the email you entered.
    You should receive them shortly.
  </p>
  <p>
    If you don't receive an email, please make sure you've entered the address you registered with,
    and check your spam folder.
  </p>
{% endblock %}

accounts/templates/accounts/password_reset_email.html
{% autoescape off %}
To initiate the password reset process for your {{ user.get_username }} TestMyApp Account,
click the link below:

{{ protocol }}://{{ domain }}{% url 'accounts:password_reset_confirm' uidb64=uid token=token %}

If clicking the link above doesn't work, please copy and paste the URL in a new browser
window instead.

Sincerely,
The TestSite Team
{% endautoescape %}

accounts/templates/accounts/signup.html
{% extends 'base.html'%}
{% load bootstrap4 %}


{% block content %}
<div class="container">
    <h1>Sign Up</h1>
    <form method="POST">
        {% csrf_token %}
        {% bootstrap_form user_form %}
        {% bootstrap_form profile_form %}
        <input type="submit" value="Sign Up" class="btn btn-default">
    </form>
</div>
{% endblock %}

accounts/templates/accounts/update_profile.html
{% extends 'base.html'%}
{% load bootstrap4 %}


{% block content %}
<div class="container">
 <form method="post">
  {% csrf_token %}
  {{ user_form.as_p }}
  {{ profile_form.as_p }}
  <button type="submit">Save changes</button>
</form>

</div>
{% endblock %}