accounts/urls.py
from django.urls import path, re_path
from accounts import views
from django.contrib.auth import views as auth_views

app_name = 'accounts'

urlpatterns = [
    re_path(r'^signup/$', views.signup, name='signup'),
    re_path(r'^login/$', auth_views.LoginView.as_view(
        template_name='accounts/login.html'), name='login'),
    re_path(r'^logout/$', auth_views.LogoutView.as_view(), name='logout'),
    #re_path(r'^my-profile/$', views.ProfileDetailView.as_view(), name='my_profile'),
    re_path(r'^update-profile/$', views.update_profile, name='update_profile'),
    re_path(r'^profile/(?P<pk>\d+)/$',
            views.ProfileDetailView.as_view(), name='view_profile_with_pk'),
    re_path(r'^change-password/$', views.MyPasswordChangeView.as_view(),
            name='change_password'),
    re_path(r'^password_reset/$', views.MyPasswordResetView.as_view(),
            name='password_reset'),
    re_path(r'^password_reset/done/$',
            views.MyPasswordResetDoneView.as_view(), name='password_reset_done'),
    re_path(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
            views.MyPasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    re_path(r'^reset/done/$', views.MyPasswordResetCompleteView.as_view(),
            name='password_reset_complete'),
]

file_upload_app/urls.py
from django.urls import re_path
from file_upload_app import views

app_name = 'album'

urlpatterns = [
    re_path(r'^album-upload/$', views.album_upload, name='album_upload'),
    re_path(r'^avatar-upload/$', views.avatar_upload, name='avatar_upload'),
    re_path(r'^album-view-by-folder/(?P<folder_name>\d+)/$', views.album_view_by_folder, name='album_view_by_folder'),
    re_path(r'^view/(?P<user>\d+)/$', views.AlbumView.as_view(), name='album_view'),
    re_path(r'^delete/(?P<image_pk>\d+)/$', views.delete_image, name='delete_image'),
]

my_django_project/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from . import settings
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    re_path(r"^$", views.HomePage.as_view(), name="home"),
    path('accounts/', include('accounts.urls')),
    path('album/', include('file_upload_app.urls')),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="/docs/4.0/assets/img/favicons/favicon.ico">

    <title>Virality</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/4.0/examples/navbar-fixed/">

    <!-- Bootstrap core CSS -->
    <link href="https://getbootstrap.com/docs/4.0/dist/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
   <style>
       body {
            min-height: 75rem;
            padding-top: 4.5rem;
            }
   </style>
    
  </head>

  <body>

    <nav class="navbar navbar-expand-md navbar-light fixed-top" style="background-color: #e3f2fd;">
      <a class="navbar-brand" href="{% url 'home' %}">Home</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarCollapse">
        {% if user.is_authenticated %}
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <a href="{% url 'album:album_view' user=request.user.id %}" class="nav-link d-flex align-items-center">
              <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" aria-hidden="true" class="mr-2" viewBox="0 0 24 24" focusable="false"><path d="M23 19a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h4l2-3h6l2 3h4a2 2 0 0 1 2 2z"></path><circle cx="12" cy="13" r="4"></circle></svg>
              Album
            </a>
           <li class="nav-item">
            <a class="nav-link" href="{% url 'accounts:view_profile_with_pk' pk=user.id %}">My profile</a>
 
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'accounts:logout' %}">Logout</a>
          </li>
        {% else %}
        <ul class="navbar-nav ml-auto">
            <li class="nav-item">
              <a class="nav-link" href="{% url 'accounts:login' %}">Login</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'accounts:signup'%}">Signup</a>
            </li>
        {% endif %}

        </ul>
        
      </div>
    </nav>

    {% block content %} {% endblock %}

    <!-- Some copied JQuery -->
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        crossorigin="anonymous"></script>
</body>
</html>

templates/index.html
{% extends "base.html" %}
{% block content %}

<div class='container'>
    <h1>Welcome to Star Social!</h1>
    <h2>The best community for all things on outer space!</h2>
    <h2>Login or Sign-up for free to get started!</h2>
</div>


{% endblock %}